# OpenBSD configuration for init.d/openbsd/zapret2.sh

# ZAPRET_DIR=/usr/local/etc/zapret2
# PF_MAIN_CONF=/etc/pf.conf
# PF_ANCHOR_NAME=zapret2
# PF_ANCHOR_FILE=/etc/pf.zapret2.conf
# PF_AUTOINSTALL_ANCHOR=1
#
# safe:
# outgoing tcp/udp + incoming tcp SYN,ACK/FIN/RST only
# full:
# full bidirectional stream interception through stateful pf
# PF_MODE=safe
#
# IFACE_WAN=em0
# PORTS_TCP=80,443
# PORTS_UDP=443
# PORT_DIVERT=989
#
# DVTWS2=/usr/local/etc/zapret2/nfq2/dvtws2
# LUA_LIB=/usr/local/etc/zapret2/lua/zapret-lib.lua
# LUA_ANTIDPI=/usr/local/etc/zapret2/lua/zapret-antidpi.lua
# DVTWS2_ARGS_FILE=/usr/local/etc/zapret2/init.d/openbsd/dvtws2.args
# DVTWS2_ARGS="--lua-desync=multisplit"
